server:
  port: 8086
  address: 0.0.0.0
spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: 268368As#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      enabled: false
eureka:
  client:
    enabled: true
