server:
  port: 8088

spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:268368As#}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderPlaced-in-0:
          destination: order-placed
        paymentConfirmed-in-0:
          destination: payment-confirmed
        deliveryStarted-in-0:
          destination: delivery-started
      rabbit:
        bindings:
          orderPlaced-in-0:
            consumer:
              exchangeType: topic
          paymentConfirmed-in-0:
            consumer:
              exchangeType: topic
          deliveryStarted-in-0:
            consumer:
              exchangeType: topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
