user_db.url=jdbc:postgresql://localhost:5432/user_db
user_db.user=postgres
user_db.pass=268368As#

auth_db.url=jdbc:postgresql://localhost:5432/auth_db
auth_db.user=postgres
auth_db.pass=268368As#

product_db.url=jdbc:postgresql://localhost:5432/product_db
product_db.user=postgres
product_db.pass=268368As#

order_db.url=jdbc:postgresql://localhost:5432/order_db
order_db.user=postgres
order_db.pass=268368As#

payment_db.url=jdbc:postgresql://localhost:5432/payment_db
payment_db.user=postgres
payment_db.pass=268368As#

delivery_db.url=jdbc:postgresql://localhost:5432/delivery_db
delivery_db.user=postgres
delivery_db.pass=268368As#

chat_db.url=jdbc:postgresql://localhost:5432/chat_db
chat_db.user=postgres
chat_db.pass=268368As#

notification_db.url=jdbc:postgresql://localhost:5432/notification_db
notification_db.user=postgres
notification_db.pass=268368As#
